import {
  Client,
  Campaign,
  Result,
  ProofPack,
  DemoUser,
  ActivityItem,
  StatCardData,
  ChartData,
  SparklineData,
} from './types';

// Helper to generate UUID-like IDs
const generateId = (): string => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

// Helper to generate recent ISO date strings
const getRecentDate = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

const getRecentMonthYear = (monthsAgo: number): string => {
  const date = new Date();
  date.setMonth(date.getMonth() - monthsAgo);
  return date.toISOString().substring(0, 7); // YYYY-MM
};

export const DEMO_USER: DemoUser = {
  id: 'user-sarahc',
  name: 'Sarah Chen',
  email: 'sarah.chen@agency.com',
  role: 'Agency Owner',
  plan: 'Pro',
  avatar: 'SC',
  joinedAt: getRecentDate(365),
};

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'client-001',
    name: 'Innovate Solutions Inc.',
    contactEmail: 'contact@innovatesol.com',
    status: 'Active',
    createdAt: getRecentDate(120),
    updatedAt: getRecentDate(5),
  },
  {
    id: 'client-002',
    name: 'Global Ventures Co.',
    contactEmail: 'partners@globalv.com',
    status: 'Active',
    createdAt: getRecentDate(90),
    updatedAt: getRecentDate(10),
  },
  {
    id: 'client-003',
    name: 'Apex Marketing Group',
    contactEmail: 'info@apexmg.net',
    status: 'Active',
    createdAt: getRecentDate(150),
    updatedAt: getRecentDate(1),
  },
  {
    id: 'client-004',
    name: 'Dynamic Innovations',
    contactEmail: 'hello@dynamicinn.io',
    status: 'Active',
    createdAt: getRecentDate(60),
    updatedAt: getRecentDate(20),
  },
  {
    id: 'client-005',
    name: 'Synergy Brands LLC',
    contactEmail: 'support@synergyb.com',
    status: 'Suspended',
    createdAt: getRecentDate(200),
    updatedAt: getRecentDate(45),
  },
  {
    id: 'client-006',
    name: 'Pinnacle Tech Corp.',
    contactEmail: 'sales@pinnacletech.net',
    status: 'Active',
    createdAt: getRecentDate(75),
    updatedAt: getRecentDate(3),
  },
  {
    id: 'client-007',
    name: 'Horizon Digital Media',
    contactEmail: 'contact@horizondm.org',
    status: 'Archived',
    createdAt: getRecentDate(300),
    updatedAt: getRecentDate(60),
  },
  {
    id: 'client-008',
    name: 'Elite Solutions Hub',
    contactEmail: 'team@elitesh.co',
    status: 'Active',
    createdAt: getRecentDate(40),
    updatedAt: getRecentDate(1),
  },
  {
    id: 'client-009',
    name: 'Velocity Growth Partners',
    contactEmail: 'reach@velocitygp.com',
    status: 'Active',
    createdAt: getRecentDate(180),
    updatedAt: getRecentDate(15),
  },
  {
    id: 'client-010',
    name: 'Quantum Analytics LLC',
    contactEmail: 'contact@quantumanalytics.net',
    status: 'Active',
    createdAt: getRecentDate(25),
    updatedAt: getRecentDate(2),
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'campaign-001',
    clientId: 'client-001',
    name: 'Q4 2024 Digital Lead Gen',
    startDate: getRecentDate(90).substring(0, 10),
    endDate: getRecentDate(30).substring(0, 10),
    objective: 'Generate 100+ qualified leads via Google Ads and social media.',
    status: 'Completed',
    createdAt: getRecentDate(95),
    updatedAt: getRecentDate(28),
  },
  {
    id: 'campaign-002',
    clientId: 'client-002',
    name: 'Brand Awareness Push H1 2025',
    startDate: getRecentDate(20).substring(0, 10),
    endDate: getRecentDate(-70).substring(0, 10), // Future date
    objective: 'Increase brand mentions by 20% and reach 1M impressions.',
    status: 'Running',
    createdAt: getRecentDate(25),
    updatedAt: getRecentDate(3),
  },
  {
    id: 'campaign-003',
    clientId: 'client-003',
    name: 'Website Redesign Launch',
    startDate: getRecentDate(100).substring(0, 10),
    endDate: getRecentDate(40).substring(0, 10),
    objective: 'Drive traffic to new website and improve conversion rates by 5%.',
    status: 'Completed',
    createdAt: getRecentDate(105),
    updatedAt: getRecentDate(35),
  },
  {
    id: 'campaign-004',
    clientId: 'client-001',
    name: 'New Product Launch - Spring',
    startDate: getRecentDate(50).substring(0, 10),
    endDate: getRecentDate(-10).substring(0, 10),
    objective: 'Achieve 500 pre-orders for new product line.',
    status: 'Running',
    createdAt: getRecentDate(55),
    updatedAt: getRecentDate(1),
  },
  {
    id: 'campaign-005',
    clientId: 'client-004',
    name: 'Social Media Engagement Boost',
    startDate: getRecentDate(70).substring(0, 10),
    endDate: getRecentDate(15).substring(0, 10),
    objective: 'Increase average engagement rate across all platforms by 1.5%.',
    status: 'Completed',
    createdAt: getRecentDate(75),
    updatedAt: getRecentDate(12),
  },
  {
    id: 'campaign-006',
    clientId: 'client-006',
    name: 'SEO Content Strategy Q2',
    startDate: getRecentDate(30).substring(0, 10),
    endDate: getRecentDate(-60).substring(0, 10),
    objective: 'Rank top 3 for 5 new keywords and increase organic traffic by 10%.',
    status: 'Running',
    createdAt: getRecentDate(32),
    updatedAt: getRecentDate(7),
  },
  {
    id: 'campaign-007',
    clientId: 'client-008',
    name: 'Email Nurture Series Update',
    startDate: getRecentDate(10).substring(0, 10),
    endDate: getRecentDate(-20).substring(0, 10),
    objective: 'Improve open rates by 3% and click-through rates by 1%.',
    status: 'Running',
    createdAt: getRecentDate(12),
    updatedAt: getRecentDate(2),
  },
  {
    id: 'campaign-008',
    clientId: 'client-009',
    name: 'Influencer Marketing Pilot',
    startDate: getRecentDate(180).substring(0, 10),
    endDate: getRecentDate(120).substring(0, 10),
    objective: 'Generate 100+ user-generated content pieces via influencer collaborations.',
    status: 'Archived',
    createdAt: getRecentDate(185),
    updatedAt: getRecentDate(118),
  },
  {
    id: 'campaign-009',
    clientId: 'client-010',
    name: 'Market Research & Analysis',
    startDate: getRecentDate(45).substring(0, 10),
    endDate: getRecentDate(5).substring(0, 10),
    objective: 'Identify key market segments and competitor strategies for Q3.',
    status: 'Completed',
    createdAt: getRecentDate(50),
    updatedAt: getRecentDate(4),
  },
  {
    id: 'campaign-010',
    clientId: 'client-002',
    name: 'Retargeting Ad Campaigns',
    startDate: getRecentDate(60).substring(0, 10),
    endDate: getRecentDate(10).substring(0, 10),
    objective: 'Improve ROAS on retargeting campaigns by 15%.',
    status: 'Completed',
    createdAt: getRecentDate(65),
    updatedAt: getRecentDate(8),
  },
];

export const MOCK_RESULTS: Result[] = [
  {
    id: 'result-001',
    campaignId: 'campaign-001',
    metricName: 'Clicks',
    value: 12500,
    unit: '#',
    dateRecorded: getRecentDate(28),
    notes: 'Strong performance on Google Ads for core keywords.',
    createdAt: getRecentDate(29),
    updatedAt: getRecentDate(28),
  },
  {
    id: 'result-002',
    campaignId: 'campaign-001',
    metricName: 'Conversions',
    value: 115,
    unit: '#',
    dateRecorded: getRecentDate(28),
    notes: 'Exceeded target of 100 qualified leads.',
    createdAt: getRecentDate(29),
    updatedAt: getRecentDate(28),
  },
  {
    id: 'result-003',
    campaignId: 'campaign-002',
    metricName: 'Impressions',
    value: 780000,
    unit: '#',
    dateRecorded: getRecentDate(3),
    notes: 'On track to meet 1M impression goal for H1.',
    createdAt: getRecentDate(4),
    updatedAt: getRecentDate(3),
  },
  {
    id: 'result-004',
    campaignId: 'campaign-003',
    metricName: 'Conversions',
    value: 8.2,
    unit: '%',
    dateRecorded: getRecentDate(35),
    notes: 'New website conversion rate increased by 2.5% points from baseline.',
    createdAt: getRecentDate(36),
    updatedAt: getRecentDate(35),
  },
  {
    id: 'result-005',
    campaignId: 'campaign-004',
    metricName: 'Leads',
    value: 380,
    unit: '#',
    dateRecorded: getRecentDate(1),
    notes: 'Pre-order campaign showing good traction, still 2 weeks to go.',
    createdAt: getRecentDate(2),
    updatedAt: getRecentDate(1),
  },
  {
    id: 'result-006',
    campaignId: 'campaign-005',
    metricName: 'Clicks',
    value: 28000,
    unit: '#',
    dateRecorded: getRecentDate(12),
    notes: 'High click-throughs on engaging video content.',
    createdAt: getRecentDate(13),
    updatedAt: getRecentDate(12),
  },
  {
    id: 'result-007',
    campaignId: 'campaign-006',
    metricName: 'Impressions',
    value: 120000,
    unit: '#',
    dateRecorded: getRecentDate(7),
    notes: 'Early signs of increased visibility from new blog posts.',
    createdAt: getRecentDate(8),
    updatedAt: getRecentDate(7),
  },
  {
    id: 'result-008',
    campaignId: 'campaign-007',
    metricName: 'Conversions',
    value: 2.1,
    unit: '%',
    dateRecorded: getRecentDate(2),
    notes: 'Initial A/B test showed 0.5% lift in CTA conversion.',
    createdAt: getRecentDate(3),
    updatedAt: getRecentDate(2),
  },
  {
    id: 'result-009',
    campaignId: 'campaign-009',
    metricName: 'Spend',
    value: 4800.75,
    unit: '$',
    dateRecorded: getRecentDate(4),
    notes: 'Budget tracking for research complete.',
    createdAt: getRecentDate(5),
    updatedAt: getRecentDate(4),
  },
  {
    id: 'result-010',
    campaignId: 'campaign-010',
    metricName: 'Spend',
    value: 3100.20,
    unit: '$',
    dateRecorded: getRecentDate(8),
    notes: 'Efficient ad spend on retargeting, 12% lower CPA.',
    createdAt: getRecentDate(9),
    updatedAt: getRecentDate(8),
  },
  {
    id: 'result-011',
    campaignId: 'campaign-001',
    metricName: 'Spend',
    value: 8450.50,
    unit: '$',
    dateRecorded: getRecentDate(28),
    notes: 'Total ad spend for Q4 campaign.',
    createdAt: getRecentDate(29),
    updatedAt: getRecentDate(28),
  },
  {
    id: 'result-012',
    campaignId: 'campaign-004',
    metricName: 'Impressions',
    value: 550000,
    unit: '#',
    dateRecorded: getRecentDate(1),
    notes: 'Visibility for new product across social channels.',
    createdAt: getRecentDate(2),
    updatedAt: getRecentDate(1),
  },
];


export const MOCK_PROOF_PACKS: ProofPack[] = [
  {
    id: 'pp-001',
    clientId: 'client-001',
    campaignId: 'campaign-001',
    name: 'Innovate Solutions - Q4 2024 Lead Gen Performance Review',
    status: 'Completed',
    summary: 'Comprehensive report on Q4 digital lead generation, highlighting key metrics, successes, and future recommendations.',
    exportUrl: '/api/exports/pp-001',
    createdAt: getRecentDate(25),
    updatedAt: getRecentDate(24),
  },
  {
    id: 'pp-002',
    clientId: 'client-002',
    campaignId: 'campaign-002',
    name: 'Global Ventures - H1 2025 Brand Awareness Strategy',
    status: 'Draft',
    summary: 'Initial draft for the H1 2025 brand awareness campaign, including strategy, projected reach, and media plan.',
    exportUrl: undefined,
    createdAt: getRecentDate(18),
    updatedAt: getRecentDate(1),
  },
  {
    id: 'pp-003',
    clientId: 'client-003',
    campaignId: 'campaign-003',
    name: 'Apex Marketing - Website Redesign Post-Launch Analysis',
    status: 'Ready for Review',
    summary: 'Detailed analysis of website redesign impact on traffic, user engagement, and conversion rates.',
    exportUrl: undefined,
    createdAt: getRecentDate(38),
    updatedAt: getRecentDate(3),
  },
  {
    id: 'pp-004',
    clientId: 'client-001',
    campaignId: 'campaign-004',
    name: 'Innovate Solutions - Spring Product Launch Prep',
    status: 'Draft',
    summary: 'Proof pack covering pre-launch activities, early traction, and media coverage plan for the new product.',
    exportUrl: undefined,
    createdAt: getRecentDate(10),
    updatedAt: getRecentDate(2),
  },
  {
    id: 'pp-005',
    clientId: 'client-004',
    campaignId: 'campaign-005',
    name: 'Dynamic Innovations - Social Media Engagement Report',
    status: 'Completed',
    summary: 'Report summarizing social media performance, engagement metrics, and audience growth over the last quarter.',
    exportUrl: '/api/exports/pp-005',
    createdAt: getRecentDate(15),
    updatedAt: getRecentDate(14),
  },
  {
    id: 'pp-006',
    clientId: 'client-006',
    campaignId: 'campaign-006',
    name: 'Pinnacle Tech - Q2 SEO Content Audit',
    status: 'Draft',
    summary: 'Audit of Q2 SEO content performance, keyword rankings, and organic traffic shifts.',
    exportUrl: undefined,
    createdAt: getRecentDate(8),
    updatedAt: getRecentDate(4),
  },
  {
    id: 'pp-007',
    clientId: 'client-008',
    campaignId: 'campaign-007',
    name: 'Elite Solutions Hub - Email Nurture Series Optimization',
    status: 'Ready for Review',
    summary: 'Review of A/B testing results and proposed optimizations for the email nurture series.',
    exportUrl: undefined,
    createdAt: getRecentDate(5),
    updatedAt: getRecentDate(1),
  },
  {
    id: 'pp-008',
    clientId: 'client-009',
    campaignId: 'campaign-008',
    name: 'Velocity Growth Partners - Influencer Pilot Wrap-Up',
    status: 'Archived',
    summary: 'Final report for the influencer marketing pilot, including reach, engagement, and content generated.',
    exportUrl: '/api/exports/pp-008',
    createdAt: getRecentDate(110),
    updatedAt: getRecentDate(108),
  },
  {
    id: 'pp-009',
    clientId: 'client-010',
    campaignId: 'campaign-009',
    name: 'Quantum Analytics - Market Research Q3 Insights',
    status: 'Completed',
    summary: 'Key findings from Q3 market research, identifying new opportunities and competitive landscape.',
    exportUrl: '/api/exports/pp-009',
    createdAt: getRecentDate(6),
    updatedAt: getRecentDate(5),
  },
  {
    id: 'pp-010',
    clientId: 'client-002',
    campaignId: 'campaign-010',
    name: 'Global Ventures - Retargeting Campaign ROI',
    status: 'Completed',
    summary: 'Proof pack demonstrating the return on investment for recent retargeting ad campaigns.',
    exportUrl: '/api/exports/pp-010',
    createdAt: getRecentDate(12),
    updatedAt: getRecentDate(11),
  },
];


export const STATS: StatCardData = {
  totalClients: {
    value: MOCK_CLIENTS.filter(c => c.status === 'Active').length,
    label: 'Active Clients',
    growth: '+12.5%',
    period: 'last month',
  },
  totalProofPacks: {
    value: MOCK_PROOF_PACKS.length,
    label: 'Total Proof Packs',
    growth: '+8.1%',
    period: 'last month',
  },
  completedPacks: {
    value: MOCK_PROOF_PACKS.filter(pp => pp.status === 'Completed').length,
    label: 'Completed This Month',
    growth: '+22.0%',
    period: 'last month',
  },
  avgTurnaround: {
    value: '3.2 days',
    label: 'Avg. Turnaround',
    growth: '-1.5 days',
    period: 'last month',
  },
};

export const CHART_DATA: ChartData = {
  labels: ['Jan W1', 'Jan W2', 'Jan W3', 'Jan W4', 'Feb W1', 'Feb W2', 'Feb W3', 'Feb W4', 'Mar W1', 'Mar W2', 'Mar W3', 'Mar W4'],
  proofPacksCreated: [12, 18, 15, 20, 25, 22, 28, 30, 35, 32, 38, 40],
  revenueGenerated: [18200, 22400, 19800, 25600, 31200, 28500, 34100, 36800, 42300, 39500, 45100, 48000],
  clientsAdded: [1, 0, 2, 1, 0, 1, 1, 0, 2, 0, 1, 1],
};

export const SPARKLINE_DATA: SparklineData = {
  totalClients: [78, 82, 79, 85, 88, 91, 93],
  totalProofPacks: [142, 158, 151, 173, 188, 165, 179],
  completedPacks: [8, 10, 7, 12, 9, 11, 14],
  avgTurnaround: [4.5, 4.2, 3.9, 3.5, 3.8, 3.2, 3.0],
};

export const RECENT_ACTIVITY: ActivityItem[] = [
  { id: generateId(), action: 'Created new Proof Pack Draft', user: 'Sarah Chen', avatar: 'SC', time: '2 minutes ago', type: 'create', relatedTo: 'Global Ventures - H1 2025 Brand Awareness Strategy' },
  { id: generateId(), action: 'Updated status of Proof Pack', user: 'Marcus Webb', avatar: 'MW', time: '15 minutes ago', type: 'update', relatedTo: 'Apex Marketing - Website Redesign Post-Launch Analysis' },
  { id: generateId(), action: 'Exported Proof Pack to PDF', user: 'Sarah Chen', avatar: 'SC', time: '1 hour ago', type: 'export', relatedTo: 'Innovate Solutions - Q4 2024 Lead Gen Performance Review' },
  { id: generateId(), action: 'Added new Campaign', user: 'Liam Nguyen', avatar: 'LN', time: '2 hours ago', type: 'create', relatedTo: 'New Product Launch - Summer' },
  { id: generateId(), action: 'Created new Client record', user: 'Sarah Chen', avatar: 'SC', time: '4 hours ago', type: 'create', relatedTo: 'FutureTech Solutions' },
  { id: generateId(), action: 'Updated Proof Pack summary', user: 'Chloe Davis', avatar: 'CD', time: 'Yesterday', type: 'update', relatedTo: 'Dynamic Innovations - Social Media Engagement Report' },
  { id: generateId(), action: 'Added new Result data', user: 'Liam Nguyen', avatar: 'LN', time: 'Yesterday', type: 'create', relatedTo: 'Q2 SEO Content Strategy' },
  { id: generateId(), action: 'Archived Proof Pack', user: 'Sarah Chen', avatar: 'SC', time: '2 days ago', type: 'archive', relatedTo: 'Velocity Growth Partners - Influencer Pilot Wrap-Up' },
  { id: generateId(), action: 'Marked Proof Pack as Ready for Review', user: 'Marcus Webb', avatar: 'MW', time: '3 days ago', type: 'update', relatedTo: 'Elite Solutions Hub - Email Nurture Series Optimization' },
  { id: generateId(), action: 'Exported Proof Pack to CSV', user: 'Chloe Davis', avatar: 'CD', time: '1 week ago', type: 'export', relatedTo: 'Quantum Analytics - Market Research Q3 Insights' },
  { id: generateId(), action: 'Created new Campaign', user: 'Sarah Chen', avatar: 'SC', time: '1 week ago', type: 'create', relatedTo: 'Digital Media Placement Q3' },
  { id: generateId(), action: 'Added new Client record', user: 'Liam Nguyen', avatar: 'LN', time: '2 weeks ago', type: 'create', relatedTo: 'Spark Innovations Ltd.' },
];

export function getById<T extends { id: string }>(arr: T[], id: string): T | undefined {
  return arr.find(x => x.id === id);
}